server:
  additionalApplications:
    - name: cluster-init
      namespace: argocd
      project: default
      source:
        repoURL: https://github.com/salamirangerover/gcp-gitops-project.git
        targetRevision: HEAD
        path: manifests/_init/applications
        directory:
          recurse: true
      destination:
        namespace: cluster-init
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: false
          selfHeal: false
      syncOptions:
        - PruneLast=true
        - CreateNamespace=true
        - ServerSideApply=true
